server:
  port: 10201
  servlet:
    context-path: /client1
#    session:
#      cookie:
#        name: CLIENT1-SESSION
  use-forward-headers: true
spring:
  resources:
    static-locations: classpath:/css
  mvc:
    static-path-pattern: /css/**
  thymeleaf:
    # For dev-time hot reloading of templates. Should be disabled in production
    cache: false

security:
  oauth2:
    client:
      client-id: clientId
      client-secret: secret
      access-token-uri: http://localhost:10101/auth/oauth/token
      user-authorization-uri: http://localhost:10101/auth/oauth/authorize
      scope: read,write
#      use-current-uri: false
#      pre-established-redirect-uri: http://localhost:10201/client1/login
    resource:
      token-info-uri: http://localhost:10101/auth/oauth/check_token
      user-info-uri: http://localhost:10101/auth/me
#      prefer-token-info: false
#    authorization:
#      check-token-access: http://localhost:10101/oauth/check_token
