server:
  port: 10101
  servlet:
    context-path: /auth

spring:
  datasource:
    url: jdbc:mysql://101.132.110.185:3306/oauth?verifyServerCertificate=false&useSSL=false&useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai&autoReconnect=true
    username: learn
    password: learn-m
    driver-class-name: com.mysql.jdbc.Driver
    driverClassName: com.mysql.jdbc.Driver

  druid:
    initial-size: 5
    max-active: 10
    min-idle: 5
    max-wait: 60000
    pool-prepared-statements: true
    max-pool-prepared-statement-per-connection-size: 20
    validation-query: SELECT 1 FROM DUAL
    validation-query-timeout: 60000
    test-on-borrow: false
    test-on-return: false
    test-while-idle: true
    time-between-eviction-runs-millis: 60000
    min-evictable-idle-time-millis: 100000
    #spring.datasource.druid.max-evictable-idle-time-millis=
    filters: stat,wall,log4j
    web-stat-filter:
      enabled: true
      url-pattern: /*
      #      exclusions: *.js,*.gif,*.jpg,*.png,*.css,*.ico,/druid/*
      session-stat-enable: true
      session-stat-max-count: 1000
      principal-session-name:
      principal-cookie-name:
      profile-enable: true
    stat-view-servlet:
      enabled: true
      url-pattern: /druid/*
      reset-enable: true
      login-username: druid
      login-password: druid
      allow: 127.0.0.1
      deny:
    filter:
      stat:
        db-type: mysql
        log-slow-sql: true
        slow-sql-millis: 2000
      wall:
        enabled: true
        db-type: mysql
        config.delete-allow: false
        config.drop-table-allow: false

  #    # 下面为连接池的补充设置，应用到上面所有数据源中
  #    # 初始化大小，最小，最大
  #    initialSize: 5
  #    minIdle: 5
  #    maxActive: 20
  #    # 配置获取连接等待超时的时间
  #    maxWait: 60000
  #    # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
  #    timeBetweenEvictionRunsMillis: 60000
  #    # 配置一个连接在池中最小生存的时间，单位是毫秒
  #    minEvictableIdleTimeMillis: 300000
  #    validationQuery: SELECT 1 FROM DUAL
  #    testWhileIdle: true
  #    testOnBorrow: false
  #    testOnReturn: false
  #    # 打开PSCache，并且指定每个连接上PSCache的大小
  #    poolPreparedStatements: true
  #    maxPoolPreparedStatementPerConnectionSize: 20
  #    # 配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙
  #    filters: stat,wall,log4j
  #    # 通过connectProperties属性来打开mergeSql功能；慢SQL记录
  #    connectionProperties:
  #    # 合并多个DruidDataSource的监控数据
  #    useGlobalDataSourceStat: true
  #    druid:
  #      stat:
  #        mergeSql: true
  #        slowSqlMillis: 5000

  redis:
    # 101.132.110.185
    host: 101.132.110.185
    password: learn-r
    port: 16379
  #    pool:
  #      max-idle: 8
  #      min-idle: 0
  #      max-active: 8
  #      max-wait: -1

  rabbitmq:
    host: 101.132.110.185
    port: 5672
    username: learn
    password: learn-r
    vhost: /

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate.dialect: org.hibernate.dialect.MySQL55Dialect
#    database-platform: org.hibernate.dialect.MySQL5Dialect

#jasypt:
#  encryptor:
#    password: api-web-app
#    algorithm: PBEWithMD5AndDES
#    keyObtentionIterations: 1000
#    poolSize: 1
#    providerName: SunJCE
#    saltGeneratorClassname: org.jasypt.salt.RandomSaltGenerator
#    stringOutputType: base64

